const USERNAME = 'ndy7stillx86ihz';
const REPO_NAME = `mataburros`;
const API_URL = `https://api.github.com/repos/${USERNAME}/${REPO_NAME}/contents/`;
const CONTENTS_URL = `https://raw.githubusercontent.com/${USERNAME}/${REPO_NAME}/main/`;
const CACHE_KEY = `${REPO_NAME}_tree`;
const CACHE_TIME_KEY = `${REPO_NAME}_tree_time`;
const CACHE_LIFETIME = 1000 * 60 * 60 * 0.5; // media hora
const RESERVED_WORDS = [
    "assets",
    "README.md",
    "LICENSE",
]
const LOADING_MSGS = [
    'Preparando magia...',
    'Invocando unicornios...',
    'Rob4ndo tus datos personales...',
    'Tejiendo arcoíris...',
    'Cargando aventuras...',
    'Sincronizando estrellas...',
    'Despertando duendes...',
    'Barruntando sortilegios...',
    'Destilando sueños...',
    'Forjando constelaciones...',
    'Ajustando pistones celestiales...',
    'Reuniendo polvos de hada...',
    'Iniciando órbita lunar...',
    'Encryptando secretos...',
    'Ordenando galaxias...',
    'Moldeando dimensiones...',
    'Alimentando dragones...',
    'Pintando auroras...',
    'Rebosando chispa creativa...',
    'Refinando brillos...',
    'Navegando en arcoíris...',
    'Susurrando hechizos...',
    'Reventando confeti...',
    'Conectando hadas pixeladas...',
    'Calculando sonrisas...',
    'Desempolvando pergaminos...',
    'Invocando sirenas...',
    'Enlatando mariposas...',
    'Afinando melodías estelares...',
    'Fermentando ideas...',
    'Preparando sorpresas...',
    'Cicatrizando errores...',
    'Trazando rutas fantásticas...',
    'Regalando destellos de color...',
    'Codificando ilusiones...',
    'Bailando con auroras boreales...',
    'Reconfigurando arcoíris...',
    'Multiplicando alegrías...',
    'Conjurando galaxias...',
    'Aspirando polen lunar...',
    'Triunfando sobre bugs...',
    'Invocando tormentas de ideas...',
    'Atando cabos sueltos...',
    'Renovando energía cósmica...',
    'Pintando sueños digitales...',
    'Llenando la nave de emoción...',
    'Haciendo malabares con bits...',
    'Sirviendo tazas de creatividad...',
    'Tejiendo fantasías...',
    'Activando modo explorador...',
    'Hallando tesoros ocultos...',
    'Ultraprocesando sonrisas...',
    'Difundiendo optimismo...',
    'Embarcando aventuras...',
    'Coloreando infinitos...',
    'Ajustando focos mágicos...',
    'Renovando hechizos...',
    'Repoblando bosques encantados...',
    'Creando sinfonías de datos...',
    'Degustando brisas de inspiración...',
    'Desplegando misterio...',
    'Añadiendo chispas de ingenio...',
    'Recargando energía creativa...',
    'Embotellando arcoíris...',
    'Teletransportando ideas...'
]